name: NodeJS with Grunt

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Library backend
      run: |
        cd backend
        npm install
        
    - name: Start backend
      run: |
        cd backend
        npm start
        
    - name: Install Library frontend
      run: |
        cd frontend
        npm install
        
    - name: Start frontend
      run: |
        cd frontend
        npm start
